language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="2.1"

install:
  - pip install tox tox-travis

script:
  - tox

matrix:
  fast_finish: true

  include:
    - { python: "3.6", env: TOXENV=docs }
