language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO="1.11"

install:
  - pip install -r requirements/ci.txt
  - pip install -e .
  - pip install tox-travis

script:
  - tox

after_success:
  - coveralls
