language: python
python:
  - "2.7"

env:
  matrix:
    - TOX_ENV=py27-1.10
    - TOX_ENV=py34-1.10
    - TOX_ENV=py35-1.10
    - TOX_ENV=py27-1.9
    - TOX_ENV=py34-1.9
    - TOX_ENV=py35-1.9
    - TOX_ENV=py27-1.8
    - TOX_ENV=py33-1.8
    - TOX_ENV=py34-1.8
    - TOX_ENV=py35-1.8
    - TOX_ENV=py27-1.7
    - TOX_ENV=py33-1.7
    - TOX_ENV=py34-1.7

install:
  - pip install -U setuptools wheel
  - python setup.py develop
  - pip install --use-wheel -U -r requirements/ci.txt
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
