[tool.pylint.MASTER]
load-plugins = [
    "pylint_strict_informational",
]


[tool.pylint.REPORTS]
msg-template = "{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}"

[tool.pylint.FORMAT]
max-line-length = "120"

[tool.pylint."MESSAGES CONTROL"]
enable = [
    "use-symbolic-message-instead",
    "useless-suppression",
]

disable = [
    "arguments-differ",
    "attribute-defined-outside-init",
    "bad-continuation",
    "cyclic-import",
    "duplicate-code",
    "fixme",
    "file-ignored",
    "import-outside-toplevel",
    "invalid-name",
    "locally-enabled",
    "locally-disabled",
    "missing-docstring",
    "no-init",
    "no-member",
    "no-self-use",
    "old-style-class",
    "protected-access",
    "redefined-variable-type",
    "superfluous-parens",
    "too-few-public-methods",
    "too-many-ancestors",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-lines",
    "too-many-locals",
    "too-many-public-methods",
    "too-many-statements",
    "ungrouped-imports",
    "unused-argument",
    "useless-return",
    "wrong-import-order",  # we have a custom isort config which pylint can't grok
]